[package]
name = "shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sea-orm = { workspace = true }
rdev = { version = "0.5.2", features = ["serialize"] }
dotenv = "0.15.0"
