[workspace]
members = [
  "packages/client",
  "packages/entity",
  "packages/migration",
  "packages/shared",
  "packages/ui",
]

[workspace.dependencies]
sea-orm = { version = "0.10.3", features = [
  "sqlx-sqlite",
  "runtime-async-std-rustls",
  "macros",
  "debug-print",
] }
