[package]
name = "ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19.3"
# shared = { path = "../shared" }
# getrandom = { version = "0.2.8", features = ["js"] }
